### ISSUE TITLE
Unit tests? 

### ISSUE THREAD

**Issue by cricket007** [yousufdev/kafka-connect-append-schema#1]
Would be nice to see example test cases for this SMT

**Comment by yousufdev** [comment]
@cricket007 Yes they are on my to do list, will try to add unit test as soon as possible

**Comment by yousufdev** [comment]
@cricket007 I have added a unit test, have a look.

**Comment by cricket007** [comment]
Any reason not to use Junit5?

**Comment by yousufdev** [comment]
@cricket007 updated.

**Comment by cricket007** [comment]
Could add more coverage for edge-cases like null messsages & schemas, but LGTM!
